# Generated by Django 4.2.1 on 2023-06-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_options_article_articl_crucial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='articl_image',
            field=models.FileField(blank=True, upload_to='', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='article',
            name='articl_crucial',
            field=models.BooleanField(default=False, verbose_name='Ключевая'),
        ),
    ]
