# Generated by Django 4.2.1 on 2023-06-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_articl_actual_alter_article_articl_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
